services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DTE_API_URL=http://dte-api:5000
    env_file:
      - ./server/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    depends_on:
      - dte-api
    restart: always

  dte-api:
    build:
      context: ./dte-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./dte-api/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
