-- Migration v106: Tabla rh_acciones_personal y registro en menu_items
CREATE TABLE IF NOT EXISTS rh_acciones_personal (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_id INT NOT NULL,
    empleado_id INT NOT NULL,
    codigo VARCHAR(30) NOT NULL,
    fecha DATE NOT NULL,
    jefe_inmediato VARCHAR(150) NULL,
    lugar_trabajo VARCHAR(150) NULL,
    tiempo_laborado ENUM('0_a_1', '1_a_5', '5_a_10', 'mas_10') NOT NULL DEFAULT '0_a_1',
    tipo_accion VARCHAR(50) NOT NULL DEFAULT 'amonestacion',
    infracciones JSON NULL,
    infraccion_otra VARCHAR(255) NULL,
    descripcion_causa TEXT NOT NULL,
    articulo_codigo_trabajo VARCHAR(255) NULL,
    accion_tomar ENUM(
        'llamado_verbal',
        'llamado_escrito_1',
        'llamado_escrito_2',
        'suspension',
        'terminacion_sin_responsabilidad',
        'despido',
        'otro'
    ) NOT NULL DEFAULT 'llamado_escrito_1',
    dias_suspension INT NULL DEFAULT 0,
    fecha_inicio_suspension DATE NULL,
    fecha_fin_suspension DATE NULL,
    accion_otra VARCHAR(255) NULL,
    recursos_humanos VARCHAR(150) NULL,
    estado_firma ENUM('pendiente', 'firmado', 'se_nego_a_firmar') NOT NULL DEFAULT 'pendiente',
    testigo_nombre VARCHAR(150) NULL,
    observaciones TEXT NULL,
    estado ENUM('borrador', 'aplicada', 'anulada') NOT NULL DEFAULT 'aplicada',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_rh_ap_company (company_id),
    INDEX idx_rh_ap_empleado (empleado_id),
    INDEX idx_rh_ap_fecha (fecha),
    CONSTRAINT fk_rh_ap_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_rh_ap_empleado FOREIGN KEY (empleado_id) REFERENCES rh_empleados(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
